blog/urls.py
from django.urls import path
from .views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostEditView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blog_post_list'),
    path('create/', BlogPostCreateView.as_view(), name='blog_post_create'),
    path('<slug:slug>/', BlogPostDetailView.as_view(), name='blog_post_detail'),
    path('<slug:slug>/edit/', BlogPostEditView.as_view(), name='blog_post_edit'),
    path('<slug:slug>/delete/', BlogPostDeleteView.as_view(),
         name='blog_post_delete'),
]

catalog/urls.py
from django.urls import path
from .views import ProductListView, ContactView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, VersionCreateView

app_name = 'catalog'  # Добавляем переменную app_name для пространства имен

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('products/create/', ProductCreateView.as_view(), name='product_create'),
    path('products/<int:pk>/update/',
         ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/delete/',
         ProductDeleteView.as_view(), name='product_delete'),
    path('products/<int:product_id>/',
         ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:product_id>/create_version/',
         VersionCreateView.as_view(), name='create_version'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('catalog/', include('catalog.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserRegisterView, UserLoginView, UserLogoutView, EmailConfirmationSentView, UserConfirmEmailView, EmailConfirmView, EmailConfirmationFailedView, UserForgotPasswordView

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),

    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(),
         name='email_confirmation_sent'),  # Письмо подтверждения отправлено
    path('confirm-email/<str:token>/', UserConfirmEmailView.as_view(),
         name='email_verified'),  # работа с токеном
    path('email-confirmed/', EmailConfirmView.as_view(),
         name='email_verified'),  # Электронная почта подтверждена
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(),
         name='email_confirmation_failed'),  # Ошибка подтверждения по электронной почте

    path('password_reset/', UserForgotPasswordView.as_view(),
         name='password_reset'),  # забыл пароль

]

catalog/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone


NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    category_name = models.CharField(
        max_length=100, verbose_name='Наименование')
    category_description = models.CharField(
        max_length=250, verbose_name='Описание')

    def __str__(self):
        return f'{self.category_name}'


class Product(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='products', default=0)

    product_name = models.CharField(
        max_length=150, verbose_name='Наименование')
    product_description = models.CharField(
        max_length=250, verbose_name='Описание')
    product_image = models.ImageField(upload_to='catalog/', default='catalog/default_image.jpeg',
                                      max_length=150, verbose_name='Изображение(превью)', **NULLABLE)
    product_category_name = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='Категория')
    product_sale_price = models.FloatField(verbose_name='Цена за штуку')
    create_date = models.DateField(
        verbose_name='Дата создания', default=timezone.now)
    update_date = models.DateField(
        verbose_name='Дата последнего изменения', default=timezone.now)
    is_published = models.BooleanField(
        default=False, verbose_name='Опубликован')

    def __str__(self):
        return f'{self.id} {self.product_name} {self.product_sale_price} {self.product_category_name}'


class Version(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.CharField(
        max_length=50, verbose_name='Номер версии')
    version_name = models.CharField(
        max_length=100, verbose_name='Название версии')
    is_current = models.BooleanField(
        default=False, verbose_name='Текущая версия')

    def __str__(self):
        return f'{self.product} - {self.version_number} ({self.version_name})'

catalog/forms.py
from django import forms
from .models import Product, Version


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['product_name', 'product_description',
                  'product_image', 'product_category_name', 'product_sale_price']
        widgets = {
            'create_date': forms.HiddenInput(),
            'update_date': forms.HiddenInput(),
        }

    def clean_product_name(self):
        forbidden_words = ['казино', 'криптовалюта', 'крипта',
                           'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        product_name = self.cleaned_data['product_name'].lower()

        for word in forbidden_words:
            if word in product_name:
                raise forms.ValidationError(f'Недопустимое слово "{word}" в названии продукта.')

        return self.cleaned_data['product_name']

    def clean_product_description(self):
        forbidden_words = ['казино', 'криптовалюта', 'крипта',
                           'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        product_description = self.cleaned_data['product_description'].lower()

        for word in forbidden_words:
            if word in product_description:
                raise forms.ValidationError(f'Недопустимое слово "{word}" в описании продукта.')

        return self.cleaned_data['product_description']


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = ['version_number', 'version_name']

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django import forms
from django.views import View
from .models import Product, Version
from .forms import ProductForm, VersionForm
import json

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponseForbidden


class ProductListView(View):
    template_name = 'catalog/home.html'

    def get(self, request):
        products = Product.objects.all()
        return render(request, self.template_name, {'products': products})


class ContactView(View):
    def get(self, request):
        return render(request, "catalog/contact.html")


class ProductDetailView(View):
    template_name = 'catalog/product_detail.html'

    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)

        # Получаем текущую версию для продукта
        current_version = Version.objects.filter(
            product=product, is_current=True).first()

        return render(request, self.template_name, {'product': product, 'current_version': current_version})


class ProductCreateView(View):
    template_name = 'product_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request):
        form = ProductForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user  # Привязываем продукт к текущему пользователю
            product.save()
            return redirect('/catalog')
        return render(request, self.template_name, {'form': form})


class ProductUpdateView(View):
    template_name = 'product_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)

        # Проверяем, является ли текущий пользователь владельцем продукта
        if request.user != product.user:
            return HttpResponseForbidden("Вы не являетесь владельцем этого продукта.")

        form = ProductForm(instance=product)
        versions = Version.objects.filter(product=product)
        version_choices = [(version.id, version.version_number)
                           for version in versions]
        current_version = versions.filter(is_current=True).first()
        form.fields['version'] = forms.ChoiceField(
            choices=version_choices, initial=current_version.id if current_version else None)

        return render(request, self.template_name, {'form': form, 'product': product})

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)

        # Проверяем, является ли текущий пользователь владельцем продукта
        if request.user != product.user:
            return HttpResponseForbidden("Вы не являетесь владельцем этого продукта.")

        form = ProductForm(request.POST, request.FILES, instance=product)

        selected_version_id = request.POST.get('version')

        if form.is_valid():
            form.save()

            if selected_version_id:
                selected_version = Version.objects.get(id=selected_version_id)
                selected_version.product = product
                selected_version.is_current = True
                selected_version.save()

            Version.objects.filter(product=product).exclude(
                id=selected_version_id).update(is_current=False)
            return redirect('/catalog')
        return render(request, self.template_name, {'form': form, 'product': product})

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(request.POST, request.FILES, instance=product)

        selected_version_id = request.POST.get('version')

        if form.is_valid():
            form.save()

            if selected_version_id:
                selected_version = Version.objects.get(id=selected_version_id)
                selected_version.product = product
                selected_version.is_current = True
                selected_version.save()

            Version.objects.filter(product=product).exclude(
                id=selected_version_id).update(is_current=False)
            return redirect('/catalog')

        return render(request, self.template_name, {'form': form, 'product': product})


class ProductDeleteView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        product.delete()
        return redirect('/catalog')


class VersionCreateView(View):
    template_name = 'catalog/version_form.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        form = VersionForm(initial={'product': product})
        return render(request, self.template_name, {'form': form, 'product': product})

    def post(self, request, product_id):
        product = get_object_or_404(Product, id=product_id)
        form = VersionForm(request.POST)
        if form.is_valid():
            version = form.save(commit=False)
            version.product = product
            version.save()
            return redirect('/catalog')
        return render(request, self.template_name, {'form': form, 'product': product})

catalog/templates/catalog/contact.html
{% extends 'layout.html' %}

{% block title %}Contact - Electronic Store{% endblock %}

{% block content %}
    <h1>Contact Us</h1>

    <p>Feel free to reach out to us for any inquiries or assistance.</p>

    <div class="row">
        <div class="col-md-6">
            <h2>Our Information</h2>
            <p>
                <strong>Electronic Store</strong><br>
                123 Tech Street<br>
                Cityville, TX 12345<br>
                Email: info@electronicstore.com<br>
                Phone: (123) 456-7890
            </p>
        </div>
        <div class="col-md-6">
            <h2>Contact Form</h2>
            <form>
                <div class="form-group">
                    <label for="name">Your Name</label>
                    <input type="text" class="form-control" id="name" placeholder="Enter your name">
                </div>
                <div class="form-group">
                    <label for="email">Your Email</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter your email">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea class="form-control" id="message" rows="4" placeholder="Type your message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'layout.html' %}
{% load custom_filters %}

{% block title %}Home - Electronic Store{% endblock %}

{% block content %}

<style>
    .product-image {
        height: 200px;
        object-fit: cover;
        width: 100%;
    }
</style>
    <h1>Welcome to our Electronic Store!</h1>

    <div class="row">
        {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{% mediapath product.product_image %}" class="card-img-top product-image" alt="{{ product.product_name }}"/>
                    <div class="card-body">
                        <h5 class="card-title">{{ product.product_name }}</h5>
                        <p class="card-text">{{ product.product_description|slice:":100" }}</p>
                        <p class="card-text">Price: ${{ product.product_sale_price }}</p>
                        

                        {% if product.version_set.exists %}
                            {% for version in product.version_set.all %}
                                {% if version.is_current == True %}
                                    <p>{{version.version_number}} {{version.version_name}}</p>
                                {% endif %}
                            {% endfor %}
                        {% endif %} 
                        <a href="{% url 'catalog:product_detail' product_id=product.id %}">View Details</a>
                        <a href="#" class="btn btn-primary">Add to Cart</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/layout.html
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Electronic Store{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href={% url 'catalog:home' %}>Electronic Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href={% url 'catalog:contact' %}>Contact</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <!-- Кнопка выхода для аутентифицированного пользователя -->
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'users:logout' %}>Logout</a>
                    </li>
                {% else %}
                    <!-- Кнопка входа для неаутентифицированного пользователя -->
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'users:login' %}>Login</a>
                    </li>
                    <!-- Кнопка регистрации для неаутентифицированного пользователя -->
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'users:register' %}>Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>

</html>

catalog/templates/catalog/product_detail.html
{% extends 'layout.html' %}
{% load custom_filters %}

{% block title %}{{ product.name }} - Electronic Store{% endblock %}

{% block content %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-6">
                <img src="{% mediapath product.product_image %}" class="img-fluid" alt="{{ product.product_name }}">
            </div>
            <div class="col-md-6">
                <h1>{{ product.product_name }}</h1>
                <p class="lead">{{ product.product_description }}</p>
                <p>Price: ${{ product.product_sale_price }}</p>
                
                {% if current_version %}
                    <p>Current Version: {{ current_version.version_number }} - {{ current_version.version_name }}</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>Create Product</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Применить обновление</button>
  </form>
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h2>Create/Edit Version</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">Save</button>
  </form>
{% endblock %}
 